apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tsuchen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tsunghao-C/tsuchen-ception.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true