global:
  edition: ce
  hosts:
    domain: localhost
    https: false
  ingress:
    tls:
      enabled: false
  deployment:
    annotations: {}

postgresql:
  install: true
  auth:
    password: "password"
    postgresPassword: "password"
  primary:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

prometheus:
  install: false

gitlab-runner:
  install: false

nginx-ingress:
  enabled: false